/**
 * The internal token the API on THIS box was booted with — resolved, never guessed.
 *
 * Two install methods write it to two different places and nothing reconciles them:
 *
 *   · bare    — `~/.openship/internal-token`, written by mintBareInternalToken below
 *               and passed to the service as INTERNAL_TOKEN (up.ts startService);
 *   · compose — INTERNAL_TOKEN in `~/.openship/compose/.env`, generated by
 *               compose.ts's `keepSecret` and handed to the api container via
 *               `env_file`. It has never had anything to do with the file above.
 *
 * A reader that picks one store by hand is correct on one install and 401s on the
 * other. `openship reset-admin-password` picked the bare one, so on EVERY compose box
 * it failed with "Reset failed: Unauthorized" — and worse, it called the MINTING
 * helper, which on a compose-only box (no bare token file) generated a brand-new
 * random token, sent that, and left the junk file behind. The api container refuses it
 * outright: DEPLOY_MODE defaults to "docker" there, and internalAuth has no
 * loopback-peer fallback outside desktop.
 *
 * Hence the split enforced here: **readers resolve, only the launcher mints.** Minting
 * a token in order to authenticate cannot work by construction — the token you just
 * created is, definitionally, not the one the running API loaded — and that is the
 * whole bug class this module exists to close. `mintBareInternalToken` has exactly one
 * caller (the bare launcher, which is what MAKES its file authoritative); everything
 * that talks to a running API goes through `resolveInternalToken` /
 * `internalTokenSources`, or through lib/loopback-api's internalFetch on top of them.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

import { COMPOSE_ENV_FILE, composeInstallExists, readComposeEnvFile } from "./compose-env";
import { INTERNAL_TOKEN_FILE, OS_DIR } from "./paths";

/**
 * Persist (or read back) the BARE service's stable INTERNAL_TOKEN.
 *
 * The bare launcher boots the API with this value, which is what makes the file the
 * authority for that install — so this is the one place a token may be created. Never
 * call it to authenticate a request: see the module comment.
 */
export function mintBareInternalToken(): string {
  if (existsSync(INTERNAL_TOKEN_FILE)) return readFileSync(INTERNAL_TOKEN_FILE, "utf8").trim();
  mkdirSync(OS_DIR, { recursive: true, mode: 0o700 });
  const token = randomBytes(32).toString("hex");
  writeFileSync(INTERNAL_TOKEN_FILE, token, { mode: 0o600 });
  return token;
}

/** The bare install's token if it's already on disk — read-only, never mints. */
function bareInternalToken(): string | null {
  try {
    return readFileSync(INTERNAL_TOKEN_FILE, "utf8").trim() || null;
  } catch {
    return null;
  }
}

export interface InternalTokenSources {
  /**
   * Tokens to try, most-likely-correct first. An empty list means "this box has no
   * API we can authenticate to" — it is never padded with a freshly minted value,
   * because a token nothing is running with is a guaranteed 401 dressed up as a try.
   */
  tokens: string[];
  /** Stores that should have yielded a token and didn't, in operator-facing words. */
  problems: string[];
}

/**
 * Every token this box could legitimately be holding, ordered by evidence.
 *
 * Compose first when a compose install exists, because that install's api container is
 * what's listening. The bare file stays a CANDIDATE rather than an alternative: a box
 * that ran bare before compose has both, and an older CLI's `ensureInternalToken` left
 * stale bare files on compose-only boxes too. Callers retry on 401, so a wrong guess
 * costs one extra loopback request instead of a failed command.
 */
export function internalTokenSources(): InternalTokenSources {
  const tokens: string[] = [];
  const problems: string[] = [];

  if (composeInstallExists()) {
    const { env, unreadable } = readComposeEnvFile();
    const composeToken = env.INTERNAL_TOKEN?.trim();
    if (composeToken) {
      tokens.push(composeToken);
    } else if (unreadable) {
      // The common shape: the stack was installed with sudo, so `.env` is root-owned
      // 0600 and this invocation simply can't see the secret. That is a permissions
      // problem with a one-word fix, and it must not surface as "Unauthorized".
      problems.push(
        `can't read ${COMPOSE_ENV_FILE} (${unreadable}) — that file holds the running stack's token, so re-run this command with sudo`,
      );
    } else {
      problems.push(
        `${COMPOSE_ENV_FILE} has no INTERNAL_TOKEN — re-run \`openship up\` to regenerate it`,
      );
    }
  }

  const bare = bareInternalToken();
  if (bare && !tokens.includes(bare)) tokens.push(bare);

  return { tokens, problems };
}

/** The token to try first, or null when this box has none. Never mints. */
export function resolveInternalToken(): string | null {
  return internalTokenSources().tokens[0] ?? null;
}

/** Why there was nothing to authenticate with — one operator-facing line. */
export function internalTokenProblem(): string {
  const { problems } = internalTokenSources();
  if (problems.length) return problems.join("; ");
  return (
    `no internal token found on this machine (looked in ${COMPOSE_ENV_FILE} and ` +
    `${INTERNAL_TOKEN_FILE}) — run \`openship up\` on this box first`
  );
}

/**
 * Why every token we hold was rejected. Distinct from the above: the files exist, the
 * API answered, and it isn't running with what's on disk — which means the running
 * process is older than the current `.env`/token file (restart it) or the port belongs
 * to a different instance entirely.
 */
export function internalTokenRejectedProblem(): string {
  const { tokens, problems } = internalTokenSources();
  const plural = tokens.length > 1 ? `both of this machine's internal tokens` : `this machine's internal token`;
  // A store we couldn't READ leads here too — a compose box with an unreadable `.env`
  // falls back to a leftover bare token, which the stack then refuses. The permissions
  // problem is the likelier explanation AND the one with a fix, so it goes first.
  const unreadable = problems.length ? `${problems.join("; ")}. ` : "";
  return (
    `${unreadable}the API rejected ${plural}. It's running with a different one — restart it ` +
    `(\`openship up\`) so it picks up the current token, or check that this port belongs to this install`
  );
}
