import { describe, expect, test } from "vitest";
import {
  EDGE_UPSTREAM_DOWN_HANDLER,
  EDGE_UPSTREAM_DOWN_HTML,
  EDGE_UPSTREAM_DOWN_LOCATION_NAME,
  EDGE_UPSTREAM_DOWN_SENTINEL,
} from "./edge-upstream-down";
import { stripComments, extractBlocks } from "../system/proxy/import/parse-utils";

/**
 * The page is embedded in an nginx `return 502 '<body>'` inside every proxying vhost, so
 * the config tokenizer is part of its contract. These are not style checks: each one of
 * them, violated, produces a config that fails `openresty -t` — which means a
 * crash-looping fresh edge, or an existing edge that refuses this and every LATER reload,
 * freezing route changes for every site on the box.
 *
 * The reasons are the same ones `edge-not-found.test.ts` documents at length; this file
 * repeats the assertions rather than the essays, because the two pages are written and
 * edited independently and a shared helper would let one drift.
 */
describe("edge upstream-down page", () => {
  test("contains no single quote — it would end the nginx token mid-page", () => {
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("'");
  });

  test("contains no $ — nginx interpolates variables in a return body", () => {
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("$");
  });

  test("is a single line — both writers must serve identical bytes", () => {
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("\n");
  });

  test("contains no # — Openship's OWN config reader cuts lines at one", () => {
    // Use rgb() for colours. A CSS hex triplet here truncates the line mid-page in
    // `stripComments`, taking its closing braces with it and breaking the brace balance
    // for every vhost the reader sees after it.
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("#");
  });

  test("keeps its braces balanced — the same reader counts them", () => {
    const open = (EDGE_UPSTREAM_DOWN_HTML.match(/\{/g) ?? []).length;
    const close = (EDGE_UPSTREAM_DOWN_HTML.match(/\}/g) ?? []).length;
    expect(open).toBe(close);
  });

  test("survives a round trip through the reader that parses these files back", () => {
    // The end-to-end version of the two above, against a vhost shaped like the ones the
    // generator emits: the handler sits at server scope, so a brace or comment character
    // escaping the page would swallow the rest of the block and the box would scan as
    // fewer sites than it serves. This is the assertion whose absence let #431's fix take
    // the migrate scan down with it.
    const conf = `# Auto-generated by Openship - do not edit manually
server {
    listen 80;
    server_name app.example.com;

${EDGE_UPSTREAM_DOWN_HANDLER}

    location / {
        proxy_pass http://127.0.0.1:3009;
    }
}

server {
    listen 443 ssl;
    server_name app.example.com;

    location / {
        proxy_pass http://127.0.0.1:3009;
    }
}
`;
    expect(extractBlocks(stripComments(conf), "server")).toHaveLength(2);
  });

  test("carries the sentinel in the first 200 bytes", () => {
    // So `curl -s https://host | head -c 200` says "our edge, upstream down" rather than
    // leaving an operator to guess whose 502 they are looking at.
    expect(EDGE_UPSTREAM_DOWN_HTML.indexOf(EDGE_UPSTREAM_DOWN_SENTINEL)).toBeGreaterThan(-1);
    expect(EDGE_UPSTREAM_DOWN_HTML.indexOf(EDGE_UPSTREAM_DOWN_SENTINEL)).toBeLessThan(200);
  });

  test("makes no external request and carries no link at all", () => {
    // The report this page fixes is a THIRD PARTY's link on an operator's error page, so
    // the absence of links is the fix, not a detail. It is also served to strangers, so a
    // third-party fetch would leak their visit and a dashboard URL would advertise
    // infrastructure.
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toMatch(/https?:\/\//);
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("<a ");
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("<script");
  });

  test("never reflects the requested hostname", () => {
    // `$host` is attacker-chosen and nginx's host validation permits `<`, `>` and `"`.
    // The `$` assertion above covers the mechanism; this names the reason so it is not
    // "fixed" by escaping and re-adding it.
    expect(EDGE_UPSTREAM_DOWN_HANDLER).not.toContain("$host");
  });

  test("answers text/html regardless of the URI's extension", () => {
    // `return` with a body types the response from the request URI, so a down app's
    // `/app.css` would be `Content-Type: text/css` with an HTML body. Clearing the map is
    // what makes `default_type` apply.
    const typesAt = EDGE_UPSTREAM_DOWN_HANDLER.indexOf("types { }");
    const defaultAt = EDGE_UPSTREAM_DOWN_HANDLER.indexOf("default_type text/html;");
    expect(typesAt).toBeGreaterThan(-1);
    expect(defaultAt).toBeGreaterThan(typesAt);
  });

  test("intercepts 502 and 504 but NEVER 503", () => {
    // 503 is reachable on purpose: `blockStatus` (403) and `rateLimit.status` (429) are
    // operator-overridable, and `limit_req_status` is 429. Branding an operator's
    // deliberate block "application unavailable" would report it as an outage.
    expect(EDGE_UPSTREAM_DOWN_HANDLER).toContain(
      `error_page 502 504 ${EDGE_UPSTREAM_DOWN_LOCATION_NAME};`,
    );
    expect(EDGE_UPSTREAM_DOWN_HANDLER).not.toMatch(/error_page[^;]*\b503\b/);
  });

  test("passes the intercepted code through — no `=` before the named location", () => {
    // Verified against openresty 1.27.1.1: with `=` the named location's own return code
    // replaces the original, collapsing a real 504 into whatever it says. Without it the
    // intercepted code survives and one body serves both. A refactor that "tidies" this
    // into `= @osh_upstream_down` silently stops 504s being reportable as 504s.
    expect(EDGE_UPSTREAM_DOWN_HANDLER).not.toContain(`= ${EDGE_UPSTREAM_DOWN_LOCATION_NAME}`);
  });

  test("is reachable only from error_page — the location name is @-prefixed", () => {
    // A named location cannot be selected by a request URI, so a visitor can never ask
    // for the error page directly and the handler can never shadow a real path.
    expect(EDGE_UPSTREAM_DOWN_LOCATION_NAME.startsWith("@")).toBe(true);
    expect(EDGE_UPSTREAM_DOWN_HANDLER).toContain(`location ${EDGE_UPSTREAM_DOWN_LOCATION_NAME} {`);
  });

  test("does not set server_tokens — that would be an http-wide side effect", () => {
    // The 404 page carries it scoped to the catch-alls on purpose. This handler is
    // emitted into EVERY proxying vhost, so carrying it here would change the `Server:`
    // header for every managed site on the box as a side effect of an error page.
    expect(EDGE_UPSTREAM_DOWN_HANDLER).not.toContain("server_tokens");
  });

  test("says the address is routed and the app is not answering", () => {
    // The one thing the page exists to communicate, and the distinction the stock
    // OpenResty 502 destroys — "nothing is deployed here" (the 404 page) vs "something
    // is, and it is not answering" (this one).
    expect(EDGE_UPSTREAM_DOWN_HTML).toContain("Application unavailable");
    expect(EDGE_UPSTREAM_DOWN_HTML).toContain("not responding");
    expect(EDGE_UPSTREAM_DOWN_HTML).toContain("noindex");
  });

  test("names no status code in the body — one page answers 502 and 504", () => {
    // The status line carries the real code. A "502" printed in the tag would be wrong
    // every time the handler was reached by a read timeout.
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("502");
    expect(EDGE_UPSTREAM_DOWN_HTML).not.toContain("504");
  });
});
