/**
 * Traefik infrastructure provider — routing + SSL for self-hosted deployments.
 *
 * Uses Traefik's dynamic file provider: writes YAML config files to a watched
 * directory. Traefik detects changes automatically — no reload needed.
 *
 * SSL is handled by Traefik's built-in ACME resolver (Let's Encrypt). When a
 * route is configured with `tls.certResolver`, Traefik auto-provisions and
 * auto-renews certificates.
 *
 * This provider works with BOTH Docker and Bare runtimes — it's independent
 * of how the application process is managed.
 *
 * Typical Traefik static config (traefik.yml):
 * ```yaml
 * providers:
 *   file:
 *     directory: /etc/traefik/dynamic
 *     watch: true
 *
 * certificatesResolvers:
 *   letsencrypt:
 *     acme:
 *       email: admin@example.com
 *       storage: /etc/traefik/acme.json
 *       httpChallenge:
 *         entryPoint: web
 * ```
 */

import {
  writeFile as fsWriteFile,
  rm as fsRm,
  mkdir as fsMkdir,
  readFile as fsReadFile,
} from "node:fs/promises";
import { dirname, join } from "node:path";

import type { CommandExecutor, RouteConfig, SslResult } from "../types";
import type { RoutingProvider, SslProvider } from "./types";

// ─── Config ──────────────────────────────────────────────────────────────────

export interface TraefikProviderOptions {
  /**
   * Directory where Traefik watches for dynamic config files.
   * Default: /etc/traefik/dynamic
   */
  configDir?: string;
  /**
   * ACME certificate resolver name (must match Traefik static config).
   * Default: "letsencrypt"
   */
  certResolver?: string;
  /**
   * Path to Traefik's ACME storage file (for reading cert info).
   * Default: /etc/traefik/acme.json
   */
  acmeStoragePath?: string;
  /**
   * Command executor for file operations.
   *
   * When provided, all file reads/writes go through the executor
   * (supporting remote servers via SSH). When omitted, uses node:fs
   * directly (local server).
   *
   * This is what enables the dual-path: same TraefikProvider, same
   * config format, works both locally and remotely.
   */
  executor?: CommandExecutor;
}

const DEFAULT_CONFIG_DIR = "/etc/traefik/dynamic";
const DEFAULT_CERT_RESOLVER = "letsencrypt";
const DEFAULT_ACME_STORAGE = "/etc/traefik/acme.json";

// ─── Implementation ──────────────────────────────────────────────────────────

/**
 * Traefik-based routing and SSL provider.
 *
 * Implements both RoutingProvider and SslProvider since Traefik handles
 * both concerns through its dynamic configuration.
 */
export class TraefikProvider implements RoutingProvider, SslProvider {
  private readonly configDir: string;
  private readonly certResolver: string;
  private readonly acmeStoragePath: string;
  private readonly executor: CommandExecutor | null;

  constructor(opts?: TraefikProviderOptions) {
    this.configDir = opts?.configDir ?? DEFAULT_CONFIG_DIR;
    this.certResolver = opts?.certResolver ?? DEFAULT_CERT_RESOLVER;
    this.acmeStoragePath = opts?.acmeStoragePath ?? DEFAULT_ACME_STORAGE;
    this.executor = opts?.executor ?? null;
  }

  // ── File operation helpers (dual-path: local or remote) ──────────────

  private async _writeFile(path: string, content: string): Promise<void> {
    if (this.executor) {
      await this.executor.writeFile(path, content);
    } else {
      await fsMkdir(dirname(path), { recursive: true });
      await fsWriteFile(path, content, "utf-8");
    }
  }

  private async _readFile(path: string): Promise<string> {
    if (this.executor) {
      return this.executor.readFile(path);
    }
    return fsReadFile(path, "utf-8");
  }

  private async _rm(path: string): Promise<void> {
    if (this.executor) {
      await this.executor.rm(path);
    } else {
      try {
        await fsRm(path);
      } catch {
        // Already gone
      }
    }
  }

  private async _mkdir(path: string): Promise<void> {
    if (this.executor) {
      await this.executor.mkdir(path);
    } else {
      await fsMkdir(path, { recursive: true });
    }
  }

  // ── Routing ──────────────────────────────────────────────────────────

  /**
   * Register a route by writing a Traefik dynamic config file.
   *
   * Creates a YAML file in the watched directory. Traefik picks it up
   * automatically within seconds.
   */
  async registerRoute(route: RouteConfig): Promise<void> {
    await this._mkdir(this.configDir);

    const slug = this.domainSlug(route.domain);
    const configPath = join(this.configDir, `${slug}.yml`);

    // Build Traefik dynamic configuration YAML
    const tlsBlock = route.tls
      ? `\n      tls:\n        certResolver: ${this.certResolver}`
      : "";

    const yaml = `# Auto-generated by Openship — do not edit manually
http:
  routers:
    ${slug}:
      rule: "Host(\`${route.domain}\`)"
      service: ${slug}
      entryPoints:
        - websecure${tlsBlock}
  services:
    ${slug}:
      loadBalancer:
        servers:
          - url: "${route.targetUrl}"
`;

    await this._writeFile(configPath, yaml);
  }

  /**
   * Remove a route by deleting its config file.
   * Traefik detects the removal and drops the route.
   */
  async removeRoute(domain: string): Promise<void> {
    const slug = this.domainSlug(domain);
    const configPath = join(this.configDir, `${slug}.yml`);
    await this._rm(configPath);
  }

  // ── SSL ──────────────────────────────────────────────────────────────

  /**
   * Provision a TLS certificate for a domain.
   *
   * With Traefik + ACME, certificate provisioning is automatic when a route
   * has `tls.certResolver` configured. This method ensures the route exists
   * with TLS enabled and returns cert info from ACME storage.
   */
  async provisionCert(domain: string): Promise<SslResult> {
    // The route should already have TLS enabled via registerRoute().
    // Traefik handles ACME challenge + cert issuance automatically.
    // We check the ACME storage for cert info.
    const certInfo = await this.readCertInfo(domain);

    if (certInfo) {
      return certInfo;
    }

    // Cert not yet available — Traefik is still provisioning.
    // Return a pending result; the caller can poll.
    return {
      domain,
      expiresAt: "",
      issuer: this.certResolver,
    };
  }

  /**
   * Renew a TLS certificate.
   *
   * Traefik auto-renews certificates 30 days before expiry. This method
   * is effectively a check + trigger: it touches the route config to ensure
   * Traefik re-evaluates the cert.
   */
  async renewCert(domain: string): Promise<SslResult> {
    // Touch the config file to trigger Traefik re-evaluation
    const slug = this.domainSlug(domain);
    const configPath = join(this.configDir, `${slug}.yml`);

    try {
      const content = await this._readFile(configPath);
      const updated = content.replace(
        /^# Auto-generated by Openship.*/,
        `# Auto-generated by Openship — renewed ${new Date().toISOString()}`,
      );
      await this._writeFile(configPath, updated);
    } catch {
      // Config file doesn't exist — nothing to renew
    }

    return this.provisionCert(domain);
  }

  // ── Helpers ──────────────────────────────────────────────────────────

  /**
   * Convert a domain to a safe slug for file names and Traefik identifiers.
   * "my-app.example.com" → "my-app-example-com"
   */
  private domainSlug(domain: string): string {
    return domain.replace(/[^a-zA-Z0-9-]/g, "-").replace(/-+/g, "-");
  }

  /**
   * Read certificate info from Traefik's ACME storage file.
   *
   * The acme.json file contains all managed certificates. We look for
   * the one matching the given domain.
   */
  private async readCertInfo(domain: string): Promise<SslResult | null> {
    try {
      const raw = await this._readFile(this.acmeStoragePath);
      const storage = JSON.parse(raw);

      // ACME storage structure: { [resolverName]: { Certificates: [...] } }
      const resolver = storage[this.certResolver];
      if (!resolver?.Certificates) return null;

      for (const cert of resolver.Certificates) {
        if (cert.domain?.main === domain || cert.domain?.sans?.includes(domain)) {
          // Parse the certificate to get expiry
          // Certificate is base64-encoded PEM
          const certPem = Buffer.from(cert.certificate, "base64").toString("utf-8");
          const expiresAt = await this.parseCertExpiry(certPem);

          return {
            domain,
            expiresAt: expiresAt ?? "",
            issuer: this.certResolver,
          };
        }
      }

      return null;
    } catch {
      return null;
    }
  }

  /**
   * Extract the expiry date from a PEM certificate.
   * Uses a simple regex on the date field — avoids heavy crypto deps.
   */
  private async parseCertExpiry(pem: string): Promise<string | null> {
    // For a proper implementation, use node:crypto X509Certificate
    try {
      const { X509Certificate } = await import("node:crypto");
      const cert = new X509Certificate(pem);
      return new Date(cert.validTo).toISOString();
    } catch {
      return null;
    }
  }
}
