import { describe, expect, it, vi } from "vitest";
import { createSessionManager, createEncryption, encryptWithKey, decryptWithKey } from "../src";
import { createHash } from "node:crypto";

describe("instance-owned deployment state", () => {
  it("isolates identical deployment IDs, prompts, subscribers and closing", async () => {
    vi.useFakeTimers();
    const a = createSessionManager();
    const b = createSessionManager();
    try {
      a.createSession("dep", "project-a");
      b.createSession("dep", "project-b");
      const logsA: string[] = [], logsB: string[] = [];
      a.subscribe("dep", (event, data) => { if (event === "log") logsA.push(data); return true; });
      b.subscribe("dep", (event, data) => { if (event === "log") logsB.push(data); return true; });
      a.appendLog("dep", { timestamp: "now", message: "only-a", level: "info" });
      expect(logsA).toHaveLength(1);
      expect(logsB).toHaveLength(0);
      const prompt = { promptId: "prompt", title: "Decide", message: "Continue?", actions: [{ id: "yes", label: "Yes" }] };
      const waitingA = a.promptUser("dep", prompt);
      const waitingB = b.promptUser("dep", prompt);
      const failed = expect(waitingA).rejects.toThrow("Platform closed");
      a.close();
      a.close();
      await failed;
      expect(b.getSession("dep")?.projectId).toBe("project-b");
      expect(b.respondToPrompt("dep", "yes")).toBe(true);
      await expect(waitingB).resolves.toBe("yes");
      b.appendLog("dep", { timestamp: "now", message: "still-b", level: "info" });
      expect(logsB).toHaveLength(1);
      expect(() => a.createSession("another", "project-a")).toThrow("closed");
    } finally {
      a.close(); b.close();
      expect(vi.getTimerCount()).toBe(0);
      vi.useRealTimers();
    }
  });

  it("accepts a synchronous native prompt response without losing the answer", async () => {
    const sessions = createSessionManager();
    try {
      sessions.createSession("dep", "project");
      sessions.subscribe("dep", (event) => {
        if (event === "prompt") sessions.respondToPrompt("dep", "yes");
        return true;
      });
      await expect(sessions.promptUser("dep", { promptId: "p", title: "T", message: "M", actions: [{ id: "yes", label: "Yes" }] })).resolves.toBe("yes");
    } finally { sessions.close(); }
  });
});

describe("instance-owned secrets", () => {
  it("decrypts a ciphertext produced by the original API implementation", () => {
    // Generated by executing apps/api/src/lib/encryption.ts from the pre-move
    // Git baseline, rather than sealing with the implementation under test.
    const legacy = "hqpRSm9qwd2SK2cNFalB5fkWiLQJTiAjnlLHZZApP+oXQq8QBVukguJVQRYwwc8RmPXDYos=";
    const secrets = createEncryption("installation-a");
    try { expect(secrets.decrypt(legacy)).toBe("stored-before-the-sdk"); }
    finally { secrets.close(); }
  });

  it("isolates keys and closing without changing the persisted ciphertext format", () => {
    const a = createEncryption("installation-a");
    const b = createEncryption("installation-b");
    const key = createHash("sha256").update("installation-a").digest();
    const sealed = a.encrypt("private");
    expect(decryptWithKey(key, sealed)).toBe("private");
    expect(a.decrypt(encryptWithKey(key, "legacy"))).toBe("legacy");
    expect(() => b.decrypt(sealed)).toThrow();
    a.close();
    expect(() => a.encrypt("closed")).toThrow("closed");
    expect(b.decrypt(b.encrypt("still-open"))).toBe("still-open");
    b.close();
  });
});
