import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { cloudflare } from '@cloudflare/vite-plugin';
import { reactRouter } from '@react-router/dev/vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import babel from 'vite-plugin-babel';
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from 'vite';
import dedent from 'dedent';

const ReactCompilerConfig = {
  /* ... */
};

export default defineConfig({
  plugins: [
    reactRouter(),
    cloudflare(),
    babel({
      filter: /\.[jt]sx?$/,
      babelConfig: {
        presets: ['@babel/preset-typescript'], // if you use TypeScript
        plugins: [['babel-plugin-react-compiler', ReactCompilerConfig]],
      },
    }),
    tsconfigPaths(),
    tailwindcss(),
    {
      name: 'add-headers',
      applyToEnvironment: (env) => env.name === 'client',
      generateBundle() {
        this.emitFile({
          fileName: '_headers',
          type: 'asset',
          source: dedent`
            # Autogenerated

            /assets/*
              ! Cache-Control
                Cache-Control: public, immutable, max-age=31536000
          `,
        });
      },
    },
    paraglideVitePlugin({
      project: './project.inlang',
      outdir: './paraglide',
      strategy: ['cookie', 'baseLocale'],
    }),
  ],
  server: {
    port: 3000,
    warmup: {
      clientFiles: ['./app/**/*', './components/**/*'],
    },
  },
  ssr: {
    // novel transitively pulls in react-tweet, which ships CSS-module
    // files. Without noExternal, Node's ESM loader chokes on .css during
    // SSR - let vite bundle these instead.
    noExternal: ['novel', 'react-tweet', '@tiptap/extension-placeholder'],
  },
  esbuild: {
    pure: ['console.log'],
  },
  build: {
    sourcemap: false,
  },
  resolve: {
    // Editor transactions require one ProseMirror instance across TipTap and direct imports.
    dedupe: ['prosemirror-model', 'prosemirror-state', 'prosemirror-view'],
    alias: {
      tslib: 'tslib/tslib.es6.js',
      'react-tweet': new URL('./lib/react-tweet-stub.ts', import.meta.url).pathname,
    },
  },
});
