-- Pasted / uploaded SSH private-key material, stored encrypted at rest (enc1:).
--
-- Nullable with no default. The existing `ssh_key_path` points at a key file on
-- the API host — useless on a remote / VPS instance where the operator's key
-- lives on their own machine. This column holds the key bytes themselves so the
-- dashboard can paste or upload a key from any browser; buildSshConfig() prefers
-- it (decrypted) over reading `ssh_key_path` off disk.
--
-- Write-only: never serialized back to the client, and listed in
-- ENCRYPTED_COLUMNS so it is stripped from any cross-host dump/restore.
ALTER TABLE "servers" ADD COLUMN IF NOT EXISTS "ssh_private_key" text;
