-- Durable, host-wide loopback-port reservations.
--
-- A port collision domain is a physical target, not an organization. Claims are
-- also deliberately detached from project/service foreign keys: a stopped app,
-- record-only delete, or cleanup-pending vhost must keep its reservation until
-- routing has been explicitly removed.
CREATE TABLE IF NOT EXISTS "host_port_claim" (
  "id" text PRIMARY KEY NOT NULL,
  "target_key" text NOT NULL,
  "port" integer NOT NULL,
  "project_id" text NOT NULL,
  "service_id" text,
  "container_port" integer,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "ck_host_port_claim_target_key"
    CHECK (
      "target_key" = 'local'
      OR "target_key" ~ '^host:[0-9a-f]{64}$'
      OR ("target_key" LIKE 'server:%' AND length("target_key") > 7)
    ),
  CONSTRAINT "ck_host_port_claim_port"
    CHECK ("port" BETWEEN 1 AND 65535),
  CONSTRAINT "ck_host_port_claim_container_port"
    CHECK ("container_port" IS NULL OR "container_port" BETWEEN 1 AND 65535)
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_host_port_claim_target_port"
  ON "host_port_claim" ("target_key", "port");
--> statement-breakpoint
-- NULLS NOT DISTINCT expressed with portable sentinels: port zero is rejected
-- above, and ids generated by Openship are never empty strings.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_host_port_claim_target_owner"
  ON "host_port_claim" (
    "target_key",
    "project_id",
    COALESCE("service_id", ''),
    COALESCE("container_port", 0)
  );
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_host_port_claim_project"
  ON "host_port_claim" ("project_id");
--> statement-breakpoint

-- Build one canonical candidate set for the whole migration. This is the same
-- set used to detect legacy ambiguity and to insert ordinary claims, so a source
-- cannot be considered by one path and silently omitted by the other.
--
-- Legacy `deployTarget:server` snapshots could omit serverId. Runtime resolves
-- those to the org's sole server; this backfill mirrors that exact org-scoped
-- fallback and collapses an isLocal server row into the local bind namespace.
WITH "sole_org_servers" AS (
  SELECT
    candidate."organization_id",
    MIN(candidate."id") AS "server_id"
  FROM "servers" candidate
  WHERE candidate."organization_id" IS NOT NULL
  GROUP BY candidate."organization_id"
  HAVING COUNT(*) = 1
),
"target_inputs" AS (
  SELECT
    'project'::text AS "context_kind",
    p."id" AS "context_id",
    COALESCE(d."organization_id", p."organization_id") AS "organization_id",
    NULLIF(d."meta" ->> 'serverId', '') AS "snapshot_server_id",
    NULLIF(p."server_id", '') AS "project_server_id",
    d."meta" ->> 'deployTarget' AS "deploy_target"
  FROM "project" p
  LEFT JOIN "deployment" d ON d."id" = p."active_deployment_id"

  UNION ALL

  SELECT
    'deployment'::text AS "context_kind",
    d."id" AS "context_id",
    d."organization_id",
    NULLIF(d."meta" ->> 'serverId', '') AS "snapshot_server_id",
    NULLIF(p."server_id", '') AS "project_server_id",
    d."meta" ->> 'deployTarget' AS "deploy_target"
  FROM "deployment" d
  INNER JOIN "project" p ON p."id" = d."project_id"
  WHERE p."active_deployment_id" = d."id"
    OR d."status" IN ('deploying', 'reconciling')
),
"resolved_target_ids" AS (
  SELECT
    input."context_kind",
    input."context_id",
    COALESCE(
      input."snapshot_server_id",
      input."project_server_id",
      CASE
        WHEN input."deploy_target" = 'server' THEN sole."server_id"
        ELSE NULL
      END
    ) AS "server_id"
  FROM "target_inputs" input
  LEFT JOIN "sole_org_servers" sole
    ON sole."organization_id" = input."organization_id"
),
"candidate_targets" AS (
  SELECT
    target."context_kind",
    target."context_id",
    CASE
      WHEN target."server_id" IS NULL OR server."is_local" = true THEN 'local'
      ELSE 'server:' || target."server_id"
    END AS "target_key"
  FROM "resolved_target_ids" target
  LEFT JOIN "servers" server ON server."id" = target."server_id"
),
-- Parse each routed service map once. Only numeric container keys and 0110's
-- explicit legacy sentinel are meaningful. Nested CASE expressions guarantee a
-- malformed hand-edited JSON value is never cast before it passes the digit gate.
"service_port_entries" AS (
  SELECT
    sd."id" AS "service_deployment_id",
    target."target_key",
    p."id" AS "project_id",
    sd."service_id",
    ports."container_key",
    parsed."container_port",
    parsed."host_port"
  FROM "service_deployment" sd
  INNER JOIN "deployment" d ON d."id" = sd."deployment_id"
  INNER JOIN "project" p ON p."id" = d."project_id"
  INNER JOIN "candidate_targets" target
    ON target."context_kind" = 'deployment'
    AND target."context_id" = d."id"
  CROSS JOIN LATERAL jsonb_each_text(COALESCE(sd."host_ports", '{}'::jsonb))
    AS ports("container_key", "host_port_text")
  CROSS JOIN LATERAL (
    SELECT
      CASE
        WHEN ports."container_key" ~ '^[0-9]{1,5}$' THEN
          CASE
            WHEN ports."container_key"::integer BETWEEN 1 AND 65535
              THEN ports."container_key"::integer
            ELSE NULL
          END
        ELSE NULL
      END AS "container_port",
      CASE
        WHEN ports."host_port_text" ~ '^[0-9]{1,5}$' THEN
          CASE
            WHEN ports."host_port_text"::integer BETWEEN 1 AND 65535
              THEN ports."host_port_text"::integer
            ELSE NULL
          END
        ELSE NULL
      END AS "host_port"
  ) parsed
  WHERE (
      p."active_deployment_id" = d."id"
      OR d."status" IN ('deploying', 'reconciling')
    )
    -- Cloud owns its own routing namespace. Persisted/imported hostPorts on a
    -- cloud release are source-host cache, never a claim on this installation.
    AND p."cloud_workspace_id" IS NULL
    AND COALESCE(NULLIF(d."meta" ->> 'deployTarget', ''), '') <> 'cloud'
    AND parsed."host_port" IS NOT NULL
    AND (
      parsed."container_port" IS NOT NULL
      OR ports."container_key" = '__legacy__'
    )
),
"candidate_claims" AS (
  -- Single-app Docker compatibility pin. Cloud bindings are excluded for the
  -- same reason as Compose maps above.
  SELECT
    'hpc_project_' || p."id" AS "id",
    target."target_key",
    p."host_port" AS "port",
    p."id" AS "project_id",
    NULL::text AS "service_id",
    NULL::integer AS "container_port"
  FROM "project" p
  LEFT JOIN "deployment" d ON d."id" = p."active_deployment_id"
  INNER JOIN "candidate_targets" target
    ON target."context_kind" = 'project'
    AND target."context_id" = p."id"
  WHERE p."host_port" BETWEEN 1 AND 65535
    AND p."cloud_workspace_id" IS NULL
    AND COALESCE(NULLIF(d."meta" ->> 'deployTarget', ''), '') <> 'cloud'

  UNION ALL

  -- Bare web processes bind their declared app port directly.
  SELECT
    'hpc_bare_' || p."id" || '_' || p."port"::text AS "id",
    target."target_key",
    p."port" AS "port",
    p."id" AS "project_id",
    NULL::text AS "service_id",
    p."port" AS "container_port"
  FROM "project" p
  INNER JOIN "deployment" d ON d."id" = p."active_deployment_id"
  INNER JOIN "candidate_targets" target
    ON target."context_kind" = 'project'
    AND target."context_id" = p."id"
  WHERE p."port" BETWEEN 1 AND 65535
    AND p."cloud_workspace_id" IS NULL
    AND COALESCE(NULLIF(d."meta" ->> 'deployTarget', ''), '') <> 'cloud'
    AND COALESCE(
      NULLIF(d."meta" ->> 'runtimeMode', ''),
      NULLIF(p."runtime_mode", '')
    ) = 'bare'
    AND COALESCE(
      NULLIF(d."meta" ->> 'workloadType', ''),
      NULLIF(p."workload_type", ''),
      CASE
        WHEN COALESCE(NULLIF(d."meta" ->> 'hasServer', ''), p."has_server"::text) = 'false'
          THEN 'static'
        ELSE 'web'
      END
    ) = 'web'

  UNION ALL

  -- Complete Compose map. A numeric key supersedes 0110's targetless legacy
  -- sentinel when both name the same host port.
  SELECT
    'hpc_service_' || entry."service_deployment_id" || '_' || entry."container_key" AS "id",
    entry."target_key",
    entry."host_port" AS "port",
    entry."project_id",
    entry."service_id",
    entry."container_port"
  FROM "service_port_entries" entry
  WHERE NOT (
    entry."container_port" IS NULL
    AND EXISTS (
      SELECT 1
      FROM "service_port_entries" numeric_entry
      WHERE numeric_entry."service_deployment_id" = entry."service_deployment_id"
        AND numeric_entry."host_port" = entry."host_port"
        AND numeric_entry."container_port" IS NOT NULL
    )
  )

  UNION ALL

  -- Scalar fallback only when the map did not already preserve this port.
  SELECT
    'hpc_service_' || sd."id" || '_scalar' AS "id",
    target."target_key",
    sd."host_port" AS "port",
    p."id" AS "project_id",
    sd."service_id",
    NULL::integer AS "container_port"
  FROM "service_deployment" sd
  INNER JOIN "deployment" d ON d."id" = sd."deployment_id"
  INNER JOIN "project" p ON p."id" = d."project_id"
  INNER JOIN "candidate_targets" target
    ON target."context_kind" = 'deployment'
    AND target."context_id" = d."id"
  WHERE (
      p."active_deployment_id" = d."id"
      OR d."status" IN ('deploying', 'reconciling')
    )
    AND p."cloud_workspace_id" IS NULL
    AND COALESCE(NULLIF(d."meta" ->> 'deployTarget', ''), '') <> 'cloud'
    AND sd."host_port" BETWEEN 1 AND 65535
    AND NOT EXISTS (
      SELECT 1
      FROM "service_port_entries" entry
      WHERE entry."service_deployment_id" = sd."id"
        AND entry."host_port" = sd."host_port"
    )
),
-- Duplicate records of the exact same claim (for example an active and carried
-- row agreeing on one port) are harmless. Pick one deterministic id.
"canonical_candidates" AS (
  SELECT
    MIN(candidate."id") AS "id",
    candidate."target_key",
    candidate."port",
    candidate."project_id",
    candidate."service_id",
    candidate."container_port"
  FROM "candidate_claims" candidate
  GROUP BY
    candidate."target_key",
    candidate."port",
    candidate."project_id",
    candidate."service_id",
    candidate."container_port"
),
"port_conflicts" AS (
  SELECT candidate."target_key", candidate."port"
  FROM "canonical_candidates" candidate
  GROUP BY candidate."target_key", candidate."port"
  HAVING COUNT(*) > 1
),
"owner_conflicts" AS (
  SELECT
    candidate."target_key",
    candidate."project_id",
    candidate."service_id",
    candidate."container_port"
  FROM "canonical_candidates" candidate
  GROUP BY
    candidate."target_key",
    candidate."project_id",
    candidate."service_id",
    candidate."container_port"
  HAVING COUNT(*) > 1
),
"ambiguous_ports" AS (
  SELECT DISTINCT candidate."target_key", candidate."port"
  FROM "canonical_candidates" candidate
  WHERE EXISTS (
      SELECT 1
      FROM "port_conflicts" conflict
      WHERE conflict."target_key" = candidate."target_key"
        AND conflict."port" = candidate."port"
    )
    OR EXISTS (
      SELECT 1
      FROM "owner_conflicts" conflict
      WHERE conflict."target_key" = candidate."target_key"
        AND conflict."project_id" = candidate."project_id"
        AND conflict."service_id" IS NOT DISTINCT FROM candidate."service_id"
        AND conflict."container_port" IS NOT DISTINCT FROM candidate."container_port"
    )
),
"final_claims" AS (
  -- An unambiguous persisted claim keeps its real stable owner.
  SELECT
    candidate."id",
    candidate."target_key",
    candidate."port",
    candidate."project_id",
    candidate."service_id",
    candidate."container_port"
  FROM "canonical_candidates" candidate
  WHERE NOT EXISTS (
    SELECT 1
    FROM "ambiguous_ports" ambiguous
    WHERE ambiguous."target_key" = candidate."target_key"
      AND ambiguous."port" = candidate."port"
  )

  UNION ALL

  -- Ambiguity is fail-closed. The reserved identity cannot match a generated
  -- project/service id, and container_port=port makes every owner tuple unique.
  SELECT
    'hpc_quarantine_' || ambiguous."target_key" || '_' || ambiguous."port"::text AS "id",
    ambiguous."target_key",
    ambiguous."port",
    '__host_port_quarantine__' AS "project_id",
    '__host_port_quarantine__' AS "service_id",
    ambiguous."port" AS "container_port"
  FROM "ambiguous_ports" ambiguous
)
INSERT INTO "host_port_claim" (
  "id",
  "target_key",
  "port",
  "project_id",
  "service_id",
  "container_port"
)
SELECT
  claim."id",
  claim."target_key",
  claim."port",
  claim."project_id",
  claim."service_id",
  claim."container_port"
FROM "final_claims" claim
ORDER BY
  claim."target_key",
  claim."port",
  claim."project_id",
  claim."service_id" NULLS FIRST,
  claim."container_port" NULLS FIRST,
  claim."id"
ON CONFLICT DO NOTHING;
