import { createAuthClient } from "better-auth/react";

const BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

/**
 * Better Auth client — connects to the Openship API.
 *
 * Uses a custom fetch wrapper with a 10s timeout so requests
 * don't hang forever when the API is unreachable.
 *
 * Methods like forgetPassword, resetPassword, sendVerificationEmail,
 * and verifyEmail are auto-generated by Better Auth's proxy client
 * when the server has the corresponding features enabled.
 */
export const authClient = createAuthClient({
  baseURL: BASE_URL,
  fetchOptions: {
    credentials: "include",
  },
});

export const {
  signIn,
  signUp,
  signOut,
  useSession,
} = authClient;

/**
 * Email / password helpers — these are proxy-generated by Better Auth
 * when the server has emailAndPassword enabled. We access them via
 * the client object so TypeScript doesn't complain about missing
 * static properties.
 */
export const forgetPassword = (authClient as any).forgetPassword as (
  opts: { email: string; redirectTo?: string },
) => Promise<{ error?: { message?: string } }>;

export const resetPassword = (authClient as any).resetPassword as (
  opts: { newPassword: string; token?: string },
) => Promise<{ error?: { message?: string } }>;

export const sendVerificationEmail = (authClient as any).sendVerificationEmail as (
  opts: { email: string; callbackURL?: string },
) => Promise<{ error?: { message?: string } }>;

export const verifyEmail = (authClient as any).verifyEmail as (
  opts: { query: { token: string } },
) => Promise<{ error?: { message?: string } }>;
