import { createAuthClient } from "better-auth/react";

/**
 * API base URL — auth requests go directly to the dedicated API server.
 *
 * Cookies on localhost are shared across ports, so Set-Cookie from :4000
 * is readable by :3001 (both browser and SSR via `cookies()`).
 *
 * In production both services share a common top-level domain
 * (e.g. api.openship.io / app.openship.io with cookie domain .openship.io).
 */
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

export const authClient = createAuthClient({
  baseURL: API_URL,
  fetchOptions: {
    credentials: "include",
    // Disable retry to prevent infinite loops on 429
    retry: {
      type: "linear",
      attempts: 0,
      delay: 0,
    },
  },
});

export const {
  signIn,
  signUp,
  signOut,
  useSession,
} = authClient;

/**
 * Email / password helpers — these are proxy-generated by Better Auth
 * when the server has emailAndPassword enabled. We access them via
 * the client object so TypeScript doesn't complain about missing
 * static properties.
 */
export const forgetPassword = (authClient as any).forgetPassword as (
  opts: { email: string; redirectTo?: string },
) => Promise<{ error?: { message?: string } }>;

export const resetPassword = (authClient as any).resetPassword as (
  opts: { newPassword: string; token?: string },
) => Promise<{ error?: { message?: string } }>;

export const sendVerificationEmail = (authClient as any).sendVerificationEmail as (
  opts: { email: string; callbackURL?: string },
) => Promise<{ error?: { message?: string } }>;

export const verifyEmail = (authClient as any).verifyEmail as (
  opts: { query: { token: string } },
) => Promise<{ error?: { message?: string } }>;
